services:
  db:
    image: postgres:latest
    container_name: postgres-ecommerce-container
    restart: always
    environment:
      POSTGRES_DB: db_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: